CREATE TABLE users (
  id         INTEGER PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50)
);

CREATE TABLE INSTALLER_COMPANY(
  INSTALLER_COMP_ID  INTEGER PRIMARY KEY,
  INSTALLER_COMP_NAME VARCHAR(30),
  INSTALLER_COMP_ADMIN VARCHAR(50),
  ADDRESS1 VARCHAR(30),
  PHONE VARCHAR(15),
  ADDRESS2 VARCHAR(30),
  STATE VARCHAR(30),
  COUNTRY VARCHAR(30),
  ZIP VARCHAR(10)
);

CREATE TABLE NODE(
  NODE_KEY  INTEGER PRIMARY KEY,
  INSTALLER_COMP_ID INTEGER,
  NODE_NAME VARCHAR(30),
  PARENT_NODE_KEY INTEGER,
  SITE_ADDRESS1 VARCHAR(30),
  SITE_ADDRESS2 VARCHAR(30),
  COUNTRY VARCHAR(30),
  ZIP VARCHAR(10),
  PHONE VARCHAR(15),
  NOTES VARCHAR(30),
  FOREIGN KEY (INSTALLER_COMP_ID) REFERENCES INSTALLER_COMPANY(INSTALLER_COMP_ID)
);

CREATE TABLE DEVICE_INFO(
  DEVICE_ID INTEGER PRIMARY KEY,
  DEVICE_TYPE VARCHAR(30),
  INSTALLER_COMP_ID INTEGER,
  NODE_KEY INTEGER,
  DEVICE_STATUS VARCHAR(30),
  FIRMWARE_VERSION_NO VARCHAR(30),
  CENTAL_STTN_ACCT_NO VARCHAR(30),
  INSTALLER_USER_ID VARCHAR(30),
  PARENT_DEVICE_ID INTEGER,
  FOREIGN KEY (NODE_KEY) REFERENCES NODE(NODE_KEY),
  FOREIGN KEY (INSTALLER_COMP_ID) REFERENCES INSTALLER_COMPANY(INSTALLER_COMP_ID )
);


CREATE TABLE DEVICE_ADDL_ATTR(
	DEVICE_ID INTEGER,
	ATTR_NAME VARCHAR(50),
	ATTR_VALUE VARCHAR(50),
	FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_INFO(DEVICE_ID) 
);

CREATE TABLE DEVICE_SERVICES(
	DEVICE_ID INTEGER,
	SERVICE_CTN VARCHAR(50),
	SERVICE_END_DATE DATE,
	SERVICE_START_DATE DATE,
	SERVICE_STATUS VARCHAR(50),
	SERVICE_NAME VARCHAR(50),
	FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE_INFO(DEVICE_ID)
);